redis:
    host: "172.17.0.3"
    port: 6379
    db: 0

graphite:
    host: "192.168.1.139"

qps_players:
    - test0:
        collect_target: "test0:bash:stats"
        collect_interval: 60
        rotate_value: 100000000
        graph_path: "test0.bash.stats"

    - test1:
        collect_target: "test1:bash:stats"
        collect_interval: 10
        rotate_value: 100000000
        graph_path: "test1.bash.stats"

aggregation_players:
    - test0:
        collect_target: "test2:bash:stats"
        collect_interval: 2
        aggregation_length: 30
        aggregation_types: max,avg
        graph_path: "test2.bash.stats"

    - test1:
        collect_target: "test3:bash:stats"
        collect_interval: 1
        aggregation_length: 60
        aggregation_types: avg 
        graph_path: "test3.bash.stats"


